package com.myway.rbac.domain;

public class RoleAuthDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_auth.role_id
     *
     * @mbg.generated
     */
    private Integer roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_auth.auth_id
     *
     * @mbg.generated
     */
    private Integer authId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_auth.role_id
     *
     * @return the value of role_auth.role_id
     *
     * @mbg.generated
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_auth.role_id
     *
     * @param roleId the value for role_auth.role_id
     *
     * @mbg.generated
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_auth.auth_id
     *
     * @return the value of role_auth.auth_id
     *
     * @mbg.generated
     */
    public Integer getAuthId() {
        return authId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_auth.auth_id
     *
     * @param authId the value for role_auth.auth_id
     *
     * @mbg.generated
     */
    public void setAuthId(Integer authId) {
        this.authId = authId;
    }
}