package com.myway.dao;

import com.myway.domain.RoleAuthDo;
import com.myway.domain.RoleAuthDoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RoleAuthDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_auth
     *
     * @mbg.generated
     */
    long countByExample(RoleAuthDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_auth
     *
     * @mbg.generated
     */
    int deleteByExample(RoleAuthDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_auth
     *
     * @mbg.generated
     */
    int insert(RoleAuthDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_auth
     *
     * @mbg.generated
     */
    int insertSelective(RoleAuthDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_auth
     *
     * @mbg.generated
     */
    List<RoleAuthDo> selectByExample(RoleAuthDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_auth
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") RoleAuthDo record, @Param("example") RoleAuthDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_auth
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") RoleAuthDo record, @Param("example") RoleAuthDoExample example);
}