package com.myway.rbac.dao;

import com.myway.rbac.domain.RoleAuthDO;
import com.myway.rbac.domain.RoleAuthDOExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface RoleAuthDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_auth
     *
     * @mbg.generated
     */
    long countByExample(RoleAuthDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_auth
     *
     * @mbg.generated
     */
    int deleteByExample(RoleAuthDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_auth
     *
     * @mbg.generated
     */
    int insert(RoleAuthDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_auth
     *
     * @mbg.generated
     */
    int insertSelective(RoleAuthDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_auth
     *
     * @mbg.generated
     */
    List<RoleAuthDO> selectByExample(RoleAuthDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_auth
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") RoleAuthDO record, @Param("example") RoleAuthDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_auth
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") RoleAuthDO record, @Param("example") RoleAuthDOExample example);
}